# SPDX-License-Identifier: MIT

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for QuarkDrive WebDAV
LUCI_DEPENDS:=+quarkdrive-webdav

PKG_LICENSE:=MIT
PKG_VERSION:=1.3.9
PKG_RELEASE:=1
PKG_MAINTAINER:=Qimiao Chen <chenqimiao1994@126.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
